FROM python:3.7
LABEL version="0.1"
LABEL purpose="python3.7-jupyter_lab"

ENV DEBCONF_NOWARNINGS yes

RUN apt-get update && apt-get install -y --quiet --no-install-recommends \
  wget

RUN pip install -q --upgrade pip

COPY ./requirements.txt ./
RUN pip install -r requirements.txt -q
RUN pip install -q jupyterlab==3.0.7

WORKDIR /work
EXPOSE 8888
#ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["jupyter", "lab", "--port", "8888", "--ip=0.0.0.0", "--allow-root"]
