FROM python:3.7
LABEL maintainer "p-geon"
LABEL version="0.1"
LABEL purpose="python3.7-base"
ENV DEBCONF_NOWARNINGS yes
RUN apt-get update && apt-get install -y --quiet --no-install-recommends \
  vim \
  wget
RUN pip install -q --upgrade pip
COPY requirements.txt ./
RUN pip install -r requirements.txt -q

WORKDIR /work
#ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["python3", "hello_world.py"]